backend:
  name: github
  repo: The-Gas-Station/gasstationcrypto.com
  branch: master
  use_graphql: true
  squash_merges: true
publish_mode: editorial_workflow
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
open_authoring: true
collections:
  - name: 'configs'
    label: 'Configs'
    files:
      - name: 'networks'
        label: 'Networks'
        file: 'src/networks.json'
        fields:
          - {
              label: 'Networks',
              name: 'networks',
              widget: 'relation',
              collection: 'networks',
              search_fields: ['display'],
              value_field: 'name',
              multiple: true,
            }
      - name: 'upcoming_events'
        label: 'Upcoming Events'
        file: 'src/upcoming_events.json'
        fields:
          - {
              label: 'Items',
              name: 'items',
              required: true,
              widget: 'list',
              fields:
                [
                  { label: 'Headline', name: 'headline', widget: 'string' },
                  { label: 'Sub Text', name: 'subText', widget: 'string' },
                ],
            }
  - name: 'networks'
    label: 'Networks'
    identifier_field: 'name'
    folder: 'src/configs'
    create: true
    extension: 'json'
    format: 'json'
    fields:
      - {
          label: 'Short Name (eth, rinkeby, bsc, polygon, fantom, etc.)',
          name: 'name',
          widget: 'string',
        }
      - { label: 'Display Name', name: 'display', widget: 'string' }
      - {
          label: 'Token Image',
          name: 'tokenImage',
          widget: 'image',
          allow_multiple: false,
          media_folder: /public/images/tokens,
        }
      - {
          label: 'Launched?',
          name: 'launched',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Launch Date',
          name: 'launchDate',
          required: false,
          widget: 'date',
          format: 'D MMM, YYYY',
        }
      - {
          label: 'Chain ID (1, 4, 56, 137, etc)',
          name: 'chainId',
          widget: 'number',
        }
      - { label: 'CoinGecko', name: 'etherCoingeckoId', widget: 'string' }
      - {
          label: 'Ether Liquidity Pair',
          name: 'etherLiquidityPair',
          required: false,
          widget: 'crypto-address',
        }
      - { label: 'Gas Token Name', name: 'gasTokenName', widget: 'string' }
      - {
          label: 'Gas Token Address',
          name: 'gasTokenAddress',
          required: false,
          widget: 'crypto-address',
        }
      - {
          label: 'Liquidity Pairs',
          name: 'liquidityPairs',
          required: false,
          widget: 'list',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Address', name: 'address', widget: 'crypto-address' },
            ],
        }
      - {
          label: 'Tokens',
          name: 'tokens',
          required: false,
          widget: 'list',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Address', name: 'address', widget: 'crypto-address' },
            ],
        }
      - {
          label: 'Pools',
          name: 'pools',
          required: false,
          widget: 'list',
          fields:
            [
              { label: 'Name', name: 'name', widget: 'string' },
              { label: 'Address', name: 'address', widget: 'crypto-address' },
              {
                label: 'Type',
                name: 'type',
                widget: 'select',
                options: ['SingleV1', 'SingleV2', 'DoubleV1'],
              },
              {
                label: 'Stake Token Image',
                name: 'stakeIcon',
                widget: 'image',
                allow_multiple: false,
                media_folder: /public/images/tokens,
              },
              {
                label: 'Reward Token Images',
                name: 'rewardIcons',
                widget: 'image',
                allow_multiple: true,
                media_folder: /public/images/tokens,
                media_library: { config: { multiple: true } },
              },
            ],
        }
